_base_: './_base_/dataset/cropland.yaml'

batch_size: 8
iters: 60000

model:
  type: LGGFormer
  in_channels: 3
  num_classes: 2
  patch_size: 3
  stage_channels: [96, 192, 384, 768]
  encoder_stage_blocks: [2, 2, 2, 2]
  decoder_stage_blocks: [2, 2, 2]
  num_heads: [2, 4, 8, 16]
  trans_layers: 2
  attn_drop: 0.5
  drop_path_rate: 0.5
  norm_type: nn.LayerNorm
  act_type: nn.GELU

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6
  learning_rate: 0.0001
  end_lr: 0.0
  power: 1.0