_base_: './_base_/dataset/cropland.yaml'

batch_size: 8
iters: 60000

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0012
  end_lr: 0
  power: 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: TopFormer
  num_classes: 2
  backbone:
    type: TopTransformer_Base
    lr_mult: 0.1
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/topformer_base_imagenet_pretrained.zip