_base_: './_base_/dataset/cropland.yaml'

batch_size: 8
iters: 60000

model:
  type: UNetFormer
  backbone:
    type: ResNet18_vd
    in_channels: 3
#    pretrained: True
  decode_channels: 64
  dropout: 0.1
  window_size: 8
  num_classes: 2

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6
  learning_rate: 0.00006
  end_lr: 0.0
  power: 1.0