_base_: './_base_/dataset/cropland.yaml'

batch_size: 8
iters: 60000

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0006
  end_lr: 0
  power: 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [ 1 ]

model:
  type: VANTopFormer
  backbone:
    type: TopTransformer
    cfgs: [
      # k,  t,  c, s
      [ 3, 1, 16, 1 ],  # 1/2
      [ 3, 4, 32, 2 ],  # 1/4 1
      [ 3, 3, 32, 1 ],  #
      [ 5, 3, 64, 2 ],  # 1/8 3
      [ 5, 3, 64, 1 ],  #
      [ 3, 3, 128, 2 ],  # 1/16 5
      [ 3, 3, 128, 1 ],  #
      [ 5, 6, 160, 2 ],  # 1/32 7
      [ 5, 6, 160, 1 ],  #
      [ 3, 6, 160, 1 ],  #
    ]
    injection_out_channels: [ 512, 512, 512, 512 ]
    encoder_out_indices: [ 2, 4, 6, 9 ]
    trans_out_indices: [ 0, 1, 2, 3 ],
    depths: 4
    key_dim: 32
    num_heads: 16
    attn_ratios: 2
    mlp_ratios: 2
    c2t_stride: 2
    drop_path_rate: 0.2
    act_layer: nn.ReLU6
    injection: True
    lr_mult: 0.1
    in_channels: 3
    tpm:
      type: VAN
      img_size: 256
      in_chans: 3
      embed_dims: [ 64, 128, 256, 512 ]
      mlp_ratios: [ 4, 4, 4, 4 ]
      drop_rate: 0.2
      drop_path_rate: 0.2
      depths: [ 3, 3, 12, 3 ]
      num_stages: 4
  head:
    type: TopFormerHead
    num_classes: 2
    in_channels: 3
    in_index: [ 0, 1, 2, 3 ],
    in_transform: multiple_select
    use_dw: False
    dropout_ratio: 0.1
    align_corners: False