batch_size: 4
iters: 40000

train_dataset:
  type: CroplandDataset
  dataset_root: D:/datasets/Cropland_Identity/new_data/data_source
  img_dir: images
  ann_dir: labels
  test_ratio: 0.3
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [256, 256]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: RandomBlur
    - type: RandomNoise
    - type: Normalize
  mode: train

val_dataset:
  type: CroplandDataset
  dataset_root: D:/datasets/Cropland_Identity/new_data/data_source
  img_dir: images
  ann_dir: labels
  test_ratio: 0.3
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: AdamW
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6
  learning_rate: 0.0008
  end_lr: 0.0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
